language: bash

sudo: required

services:
    mysql

os:
    linux

before_script:
    service --status-all; ls /var; ls /var/run; mysql -e 'CREATE DATABASE travistest;'X

script:
    TRAVIS_RUN=true dev/tests/run_tests.sh
