language:
    bash

dist: trusty
sudo: required
addons:
  apt:
    packages:
    - mysql-server
    - mysql-client

os:
    linux
    osx

before_script:
    service --status-all; mysql -e 'CREATE DATABASE travistest;'

script:
    TRAVIS_RUN=true dev/tests/run_tests.sh
