language:
    bash

dist: trusty
sudo: required

services:
    mysql

os:
    linux
    osx

before_script:
    alias mysql='mysql --socket=/run/mysql-5.6/mysqld.sock; mysql -e 'CREATE DATABASE travistest;'

script:
    TRAVIS_RUN=true dev/tests/run_tests.sh
