language:
    bash

dist: precise
sudo: required

service
    mysql

os:
    linux
    osx

before_script:
    service --status-all; mysql -e 'CREATE DATABASE travistest;'

script:
    TRAVIS_RUN=true dev/tests/run_tests.sh
