language: php

sudo: required

services:
    - mysql

os:
    linux

before_script:
    service --status-all; ls /var/run; netstat -natp; mysql -e 'CREATE DATABASE travistest;'X

script:
    TRAVIS_RUN=true dev/tests/run_tests.sh
