language:
    bash

dist: trusty
sudo: required

addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

services:
    mysql

os:
    linux
    osx

before_script:
    ls /var/run; ls /run; alias mysql='mysql --socket=/run/mysql-5.6/mysqld.sock'; mysql -e 'CREATE DATABASE travistest;'

script:
    TRAVIS_RUN=true dev/tests/run_tests.sh
