language:
    bash

sudo: required

addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6

service
    mysql

os:
    linux
    osx

before_script:
    service --status-all; mysql -e 'CREATE DATABASE travistest;'

script:
    TRAVIS_RUN=true dev/tests/run_tests.sh
