language:
    bash

services:
    mysql

os:
    linux
    osx

sudo:
    required

before_script:
    which mysql && until mysql -u root -e "show status" &>/dev/null; do echo "Waiting for MySQL to start..."; sleep 5; done
    mysql -e 'CREATE DATABASE travistest;'

script:
    TRAVIS_RUN=true dev/tests/run_tests.sh
