# Necessary evil: if 'bash' is selected as language, travis will try to install ruby and fails
language: php

sudo: required

services:
    - mysql

os:
    linux

before_script:
    mysql -e 'CREATE DATABASE travistest;'

script:
    TRAVIS_RUN=true dev/tests/run_tests.sh
